### ISSUE TITLE
Do you need any help on this?

### ISSUE THREAD

**Issue by p0wer0n** [louis-haddrell/Yik-Yak-API#1]
I've been looking at your code, and it seems to be going along great! Do you need any userIDs to test with, or links to other partially reverse engineered code and APIs of both the app and web beta? This repo has a lot of potential.

**Comment by louis-haddrell** [comment]
Thanks! Any links for info about the web API would be much appreciated :smile:

**Comment by p0wer0n** [comment]
Sorry this took so long. These repos could prove helpful:
https://github.com/deveyNull/YikYakTerminal - A branch of a popular project that has some web beta documentation
https://github.com/Mimerme/Yak-Hax - A somewhat up to date, well documented Yik Yak API written in Java. I haven't tested it yet completely, but it has some new API functions that the other API's don't have. The wiki page is nice.
https://github.com/whaatt/Pyak - A nice API that I use
https://github.com/ThePantsThief/YakKit - An Obj-C API
https://github.com/djtech42/YikYakTerminal/issues - The issue section of YikYakTerminal contains a lot of help and documentation.
I might add some more as I think about them.
UPDATE:
This is a repo created by one of Yik Yak's own employees:
https://github.com/brextonpham/iOS-AFourYearOldsYikYak
