### ISSUE TITLE
can't login with phone

### ISSUE THREAD

**Issue by ElectrumDevelopment** [louis-haddrell/Yik-Yak-API#10]
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: 

When I try to login for the first time and get the userID

**Comment by louis-haddrell** [comment]
I've just tested this and I'm able to login successfully.

Have you successfully logged in before now?

**Comment by ElectrumDevelopment** [comment]
well it never asked me got my phone number when I signed up for a new acc. My old one works sometimes. weird
