### ISSUE TITLE
Picture Yaks

### ISSUE THREAD

**Issue by ElectrumDevelopment** [louis-haddrell/Yik-Yak-API#11]
Is there any way to post pictures?

**Comment by louis-haddrell** [comment]
Previously it wasn't possible to post pictures using yikyak.com. I see they've added that function now so I will take a look!

**Comment by ElectrumDevelopment** [comment]
I've been learning how to sniff (inspired by you). Currently trying to make an API for an app called spout but the app doesn't even load when I put my http sniffing proxy on. Figured they are pinning their ssl certificate.

**Comment by ElectrumDevelopment** [comment]
I think they changed their posting API, as posts aren't going through

**Comment by louis-haddrell** [comment]
Newest commit should allow for uploading images with Yaks :)

I haven't had any problems posting though... If posts still aren't going through just open a new issue and I'll take a look!

**Comment by ElectrumDevelopment** [comment]
Is the image just the path to the image?

**Comment by louis-haddrell** [comment]
You'll need to open the file and pass the actual file object, not just the path
