### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by akashlevy** [louis-haddrell/Yik-Yak-API#2]
I was thinking about making a web client myself because of the API changes for the mobile platform (now it's impossible to post Yaks with the mobile library I wrote a while back (https://github.com/akashlevy/Yaklient)). I might be interested in incorporating this into Yaklient sometime in the future :)

**Comment by p0wer0n** [comment]
I have a private fork combining both YikYakTerminal and Yaklient and posting works for verified user ID's perfectly, and UserID generation and voting works perfectly. I'll send it to you guys if you want. I also recently discovered how to enter a secret debug panel in the app on jailbroken phones, allowing you to use links, change API endpoints, and generate new UserIDs freely. I'll share when I can.

**Comment by p0wer0n** [comment]
I've gotten very good at python since I asked a few months back what init.py did.

**Comment by akashlevy** [comment]
Awesome, I'd love to see these things and the features you discovered via jail breaking

**Comment by louis-haddrell** [comment]
Those features would be very cool to see :smile:
