### ISSUE TITLE
410 not found

### ISSUE THREAD

**Issue by ElectrumDevelopment** [louis-haddrell/Yik-Yak-API#7]
The url for getting new yaks isn't valid anymore...

"HTTPError: 410 Client Error: Gone for url: https://www.yikyak.com/api/proxy/v1/messages/all/new"

**Comment by jdleo** [comment]
They might have changed api endpoints.. nothing a little sniffing can't do.. one sec

**Comment by ElectrumDevelopment** [comment]
thanks :)

**Comment by louis-haddrell** [comment]
Looks like YikYak have updated to v2 of their API. They made a lot of annoying changes but I think I've managed to sort everything out with the latest commits.

Give it a try and let me know! :)

**Comment by ElectrumDevelopment** [comment]
Whats the base URL for yakker?

**Comment by louis-haddrell** [comment]
The base_url comes from WebObject and is https://www.yikyak.com/api/v2/
