### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by bvoelz19** [louis-haddrell/Yik-Yak-API#9]
Hi there,
First, thanks for the helpful API.
Running into this error message:

`File "/Users/Brendan/Downloads/Yik-Yak-API-master/yikyakapi/web.py", line 43, in _request
    response.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests-2.12.1-py2.7.egg/requests/models.py", line 884, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.yikyak.com/api/auth/pair`

Any ideas why I would be getting this message?

**Comment by louis-haddrell** [comment]
Hey,

Can you add a code example?

Also, just a heads up that this API was written for Python 3. I doubt it will even work with Python 2.7!

**Comment by bvoelz19** [comment]
Ah, that could be the problem. But, I just tried updating to Python 3 and tried running my test script (which follows your README) and it's been giving me lots of "No module named 'requests'" type of errors. Here's my test code:


```python
from yikyakapi.web import WebObject
from yikyakapi.yikyak import YikYak


web = WebObject()
COUNTRY_CODE = "USA"
PHONE_NUMBER = "0000000000"

if __name__ == "__main__":
	client = YikYak()
	pin = input("Web authentication PIN: ")
	client.login(COUNTRY_CODE, PHONE_NUMBER, pin)

user_id = client.yakker.user_ID
print("User ID: ", user_id)

USER_ID = 'JumboVibes'
client.login_id(COUNTRY_CODE, PHONE_NUMBER, USER_ID)

yaks = client.get_new_yaks(42.407184, -71.119751)
print("Yaks: ")
for key in yaks:
	print(yaks)

client.compose_yak("Hello world!", 42.407184, -71.119751)
```

**Comment by louis-haddrell** [comment]
OK, I see what the issue is. I've updated the README which should hopefully make things clearer.

Instead of using your handle, JumboVibes, you need to use 

To resolve your import errors make sure requests is installed for Python 3 as well.



Instead of using your handle to login, you must use the user ID that was printed.

**Comment by louis-haddrell** [comment]
OK, I see what the issue is :)

Instead of using your handle, JumboVibes, you need to use the user ID - the long string printed by this line:

```python
print("User ID: ", user_id)
```

To resolve the import errors, you probably just need to install requests for Python 3. You should be able to do this just by running `pip3 install requests` at the command prompt.

**Comment by bvoelz19** [comment]
Okay, thanks! Now I'm hitting that HTTP error again, though. Here's my code:

```python
from yikyakapi.yikyak import YikYak

COUNTRY_CODE = "USA"
PHONE_NUMBER = "3392251289"
USER_ID = 'XXXXXXX'

if __name__ == "__main__":
	client = YikYak()
	client.login(COUNTRY_CODE, PHONE_NUMBER, USER_ID)
	client.compose_yak("Hello world!", 42.407190, -71.119772, True)
```

It's giving me the following error:
```
Traceback (most recent call last):
  File "jumbovibes.py", line 9, in <module>
    client.login(COUNTRY_CODE, PHONE_NUMBER, USER_ID)
  File "/Users/Brendan/Desktop/Projects/GoodSamaritan/yikyakapi/yikyak.py", line 32, in login
    access_token = self.pair(country_code, phone_number, pin)
  File "/Users/Brendan/Desktop/Projects/GoodSamaritan/yikyakapi/yikyak.py", line 90, in pair
    response = self._request('POST', url, json=json)
  File "/Users/Brendan/Desktop/Projects/GoodSamaritan/yikyakapi/web.py", line 43, in _request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.yikyak.com/api/auth/pair
```

**Comment by louis-haddrell** [comment]
You need to call `login_id()` instead. Try this:

```python
if __name__ == "__main__":
	client = YikYak()
	client.login_id(COUNTRY_CODE, PHONE_NUMBER, USER_ID)
	client.compose_yak("Hello world!", 42.407190, -71.119772, True)
```
